project:
  type: website
  render:
    - "*.qmd"
    - "!notebooks/"
    - "!scripts/"
  #post-render: mv *.ipynb notebooks/

website:
  title: "BioFindr Tutorials"
  navbar:
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - installation.qmd
      - section: "Basic usage"
        contents:
          - coexpression.qmd
          - association.qmd
          - causal-inference.qmd
          - dag.qmd
      - section: "Advanced topics"
        contents: 
          - internal-functions-1.qmd
          - matrix-data.qmd
          - parallelization.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto

