project:
  type: website

website:
  title: "Findr Tutorials"
  navbar:
    left:
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - installation.qmd
      - section: "First steps"
        contents:
          - coexpression.qmd
          - association.qmd
          - causal-inference.qmd
      - section: "Advanced topics"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



